# -*- coding: utf-8 -*-

import flask
from flask.ext.cors import CORS

__VIEWS__ = ['example']
app = flask.Flask(__name__)
CORS(app)

STATUS_OK = 200
STATUS_CREATED = 201
STATUS_DELETED = 204
STATUS_UNAUTHORIZED = 401
STATUS_NO_CONTENT = 404
STATUS_BAD_REQUEST = 400
STATUS_NOT_ACCEPTABLE = 406
STATUS_CONFLICT = 409
STATUS_PRECONDITION_REQUIRED = 428
STATUS_INTERNAL_SERVER_ERROR = 500
